### ISSUE TITLE
Configuration phase: which color light shows "no available" in SmartThings mobile app

### ISSUE THREAD

**Issue by vitalets** [SmartThingsCommunity/weather-color-light-smartapp-nodejs#5]
Response in webhook:
```yml
CONFIGURATION response:
configurationData: 
  page: 
    pageId:         1
    name:           Bulb color by temperature
    nextPageId:     null
    previousPageId: null
    complete:       true
    sections: 
      - 
        name:     For the temperature at this US zip code
        settings: 
          - 
            id:          zipCode
            name:        What 5-digit US Zip Code?
            description: Enter Zip Code
            type:        NUMBER
            required:    true
          - 
            id:          forecastInterval
            name:        How many hours in the future to check?
            description: Tap to set
            type:        ENUM
            required:    true
            multiple:    false
            options: 
              - 
                id:   forecast-hours-3
                name: 3 Hours
              - 
                id:   forecast-hours-6
                name: 6 Hours
              - 
                id:   forecast-hours-9
                name: 9 Hours
              - 
                id:   forecast-hours-12
                name: 12 Hours
          - 
            id:          scheduleInterval
            name:        How often to check forecast?
            description: Tap to set
            type:        ENUM
            required:    true
            multiple:    false
            options: 
              - 
                id:   schedule-interval-15-minutes
                name: 15 Minutes
              - 
                id:   schedule-interval-30-minutes
                name: 30 Minutes
              - 
                id:   schedule-interval-45-minutes
                name: 45 Minutes
              - 
                id:   schedule-interval-60-minutes
                name: 60 Minutes
      - 
        name:     Set the color of this light
        settings: 
          - 
            id:           colorLight
            name:         Which color light?
            description:  Tap to set
            type:         DEVICE
            required:     true
            multiple:     false
            capabilities: 
              - colorControl
              - switch
              - switchLevel
            permissions: 
              - r
              - x
```

But in SmartThings mobile app I can only setup `zipCode`, `forecastInterval` and `scheduleInterval`.
`colorLight` does not react on taps and does not shows any data.
![image](https://user-images.githubusercontent.com/1473072/48786690-6d9f4880-ecf8-11e8-87b1-b73d7c7f1166.png)
